### PR TITLE
Class Schedule with weekly schedule sending method

### PR DESCRIPTION
**Pull request by AbhithaVish**
## Purpose

The purpose of this PR is to fix #<issue-number>

Class Schedule with weekly schedule sending method

Note  :
In the link it does not align with the background rectangle. I request to Fix that issue as well 

### After solving the issue
  

https://github.com/Cyber-III/Student-Management-System/assets/162031145/99e6f40b-4bd5-4b3d-8d01-5ac8a6490d89

 

##  Checklist
- [x] I created this pull request for the issue that was assigned to me
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by RamithaHeshan33** [comment]
> ## Purpose
> The purpose of this PR is to fix #
> 
> Class Schedule with weekly schedule sending method
> 
> Note : In the link it does not align with the background rectangle. I request to Fix that issue as well
> 
> ## Screenshots or Videos
> ### Before solving the issue
> ### After solving the issue
>  weekly.schedule.mp4 
> ## Checklist
> * [x]  I created this pull request for the issue that was assigned to me
> * [x]  I have performed a self-review of my own code
> * [x]  I have commented on my code, particularly in hard-to-understand areas

@AbhithaVish Shall we update this as the schedule takes from the database? And please use the UI as the graduation schedules page.

**Comment by RamithaHeshan33** [comment]
@AbhithaVish Shall we update this as the schedule takes from the database? And please use the UI as the graduation schedules page.

**Comment by AbhithaVish** [comment]
@RamithaHeshan33 I think you might now have  idea about the where is the link is coming. I already link the database table with the PHP code. So now I upload weekly schedule to the drive and that link is put into the database table.  No any hardcoded links is here.
I hope you understand what I am saying is.

**Comment by AbhithaVish** [comment]
@RamithaHeshan33 I already use the graduation UI. But the link is not fix that's why I ask to correct that.

**Comment by RamithaHeshan33** [comment]
Okay. I will update next part.

**Review by RamithaHeshan33 — APPROVED** [review]

**Pull request merged**
