### PR TITLE
Course Materials page batch No getting as a value 0

### LINKED ISSUE #113: Course Materials page batch No getting as a value 0
**Describe the bug**

Course Materials page batch No getting as a value 0

**Describe the Solution**

**Screenshots**

**Are you working on it**
Yes

### PR DESCRIPTION
**Pull request by AbhithaVish**
## Purpose

The purpose of this PR is to fix #113 

### After solving the issue
  
image

image

##  Checklist
- [] I created this pull request for the issue that was assigned to me
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by AbhithaVish** [comment]
@Sathinmanitha @RamithaHeshan33 @Raiden-git Course Materials page issue

**Comment by RamithaHeshan33** [comment]
> @Sathinmanitha @RamithaHeshan33 @Raiden-git Course Materials page issue

@AbhithaVish  There are some issues in the template.php file (Before Issue)

**Comment by AbhithaVish** [comment]
@RamithaHeshan33 can remove that template.php file. it was a unnecessary edit. Issue is in the other file and it was working now.

**Comment by AbhithaVish** [comment]
image

this was the commit that I changed through this issue

**Comment by RamithaHeshan33** [comment]
@AbhithaVish please check again and push

**Pull request closed without merging**
