### PR TITLE
Admin notice board changes

### PR DESCRIPTION
**Pull request by AbhithaVish**
## Purpose

The purpose of this PR is to fix #<issue-number>
[Admin notice board changes](https://github.com/Cyber-III/Student-Management-System/commit/44fec34276eb24d36a1b643064fbaa0505434067)

### Before solving the issue
notice board before

### After solving the issue
  
image

##  Checklist
- [x] I created this pull request for the issue that was assigned to me
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by RamithaHeshan33** [comment]
@AbhithaVish I think this is already updated...

Screenshot 2024-06-26 215511

**Comment by AbhithaVish** [comment]
Nope there were some changes too

**Comment by AbhithaVish** [comment]
@RamithaHeshan33 Add notice changed as save notice, "Manage" changed as "View all". Inside that "Manage" changed as edit

**Comment by RamithaHeshan33** [comment]
> @RamithaHeshan33 Add notice changed as save notice, "Manage" changed as "View all". Inside that "Manage" changed as edit

Ok. please style this "Save Changes" and "Delete Notice" buttons. please use the .view-link and .delete-link styles

Screenshot 2024-06-27 075913

**Comment by AbhithaVish** [comment]
Now completed that as well

image

**Review by RamithaHeshan33 — APPROVED** [review]

**Pull request merged**
