### PR TITLE
Mitigation Form update with assignment_name

### PR DESCRIPTION
**Pull request by AbhithaVish**
## Purpose

The purpose of this PR is to fix #<issue-number>
Mitigation Form update with assignment_name

### After solving the issue
  

https://github.com/Cyber-III/Student-Management-System/assets/162031145/90ec54e1-a5cd-42f3-b8b0-da8bfd79f2d6

##  Checklist
- [x] I created this pull request for the issue that was assigned to me
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by AbhithaVish** [comment]
@RamithaHeshan33 Module_name changed with assignment_name

**Comment by AbhithaVish** [comment]
@RamithaHeshan33 Note that View Mitigation page is not completed yet. So don't review that page

**Comment by RamithaHeshan33** [comment]
@AbhithaVish I told you to use the **Assignment Name** instead of the **Module Code**, not the **Module Name**. Please update this as below.

Screenshot 2024-06-01 082702

And remember, when you have to make some changes to your PR, you don't need to delete the existing PR and create a new PR. All you have to do is do those particular changes and push it. All the changes that you made will be updated on your existing PR.

**Comment by AbhithaVish** [comment]
@RamithaHeshan33 I try that but didn't work properly, if we use module_name. It will show every data which has same name including other courses also. but I think these options are fine for the mitigation request. user can select a assignment which is unique for their batch. and then  module_code dose the same part as well as module_name. user dose not want to type that coded, system will automatically show the module_code according to the user selected assignment

**Comment by RamithaHeshan33** [comment]
> @RamithaHeshan33 I try that but didn't work properly, if we use module_name. It will show every data which has same name including other courses also. but I think these options are fine for the mitigation request. user can select a assignment which is unique for their batch. and then module_code dose the same part as well as module_name. user dose not want to type that coded, system will automatically show the module_code according to the user selected assignment

Okay I will see.

**Review by RamithaHeshan33 — APPROVED** [review]

**Pull request merged**
